### ISSUE TITLE
节点搭建

### ISSUE THREAD

**Issue by zhaozongwen** [whatqiu/whatqiu.github.io#1]
看到了你的Blog节点搭建教程，在速度方面你可以参考一下cloudflare，或者使用hy协议；看你节点搭建好像也没有使用x-ui，建议看看相关博客，谷歌上还是很多的。没看到你在git上留Email，就这样回复了，如有打扰很抱歉。

**Comment by whatqiu** [comment]
谢谢你的建议，我用了x-ui,但是前几天IP被GFW禁了，第一次搭建哈哈哈哈，而且教程漏了点东西。再次感谢了！
